sudo: required
services: 
  - docker

before_install:
  - docker build -t ranew/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true ranew/docker-react npm run test -- --watchAll=false